### PR TITLE
Add feeding guidelines section and placeholder page

### PR DESCRIPTION
**Pull request by AlexVCS**
working to close issue #2

### CODE REVIEW

**Comment by SanditZZ** [comment]
@AlexVCS 
Awesome! Could you please add the page onto the sidebar as well? Thanks!
Docs: https://vitepress.dev/reference/default-theme-sidebar#sidebar

**Comment by AlexVCS** [comment]
> @AlexVCS Awesome! Could you please add the page onto the sidebar as well? Thanks! Docs: https://vitepress.dev/reference/default-theme-sidebar#sidebar

Think I did, here's the code in `config.mts`:

```
sidebar: [
      {
        text: "Why Cat Docs?",
        items: [{text: "Why", link: "/why-cat-docs/why"}],
      },
      {
        text: "Statistics",
        items: [{text: "Breeds", link: "/statistics/breeds"}],
      },
      {
        text: "Feeding Guidelines",
        items: [{text: "Feeding Guidelines", link: "/feeding-guidelines/yum"}],
      },
    ],
```

**Comment by AlexVCS** [comment]
Please let me know if I need to add more or change it!

**Comment by SanditZZ** [comment]
Ok! Looks fine to me 👍

**Review by SanditZZ — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
